### ISSUE TITLE
Iperf test passing despite error

### ISSUE THREAD

**Issue by Ham22** [CreatorDev/boardfarm#40]
The logs for iperf tests show these error messages `/bin/ash: mpstat: not found` yes the test still passes?

**Comment by nikhil-zinjurde-imgtec** [comment]
worth checking the test code:

    def mpstat_ok(self):
        board.sendline('mpstat -V')
        if board.expect(['sysstat version', 'BusyBox', 'not found'], timeout=5) == 0:
            mpstat_present = True
        else:
            mpstat_present = False
        board.expect(prompt)

    return mpstat_present

Clearly, not a failure

**Comment by Shpinkso** [comment]
should "not found" be a pass in our case?
